### ISSUE TITLE
Correct HRNetV2 implementation TODO

### ISSUE THREAD

**Issue by Luonic** [Luonic/semi-supervised_semantic_segmentation#3]
- [x] Num blocks per stage: stage 1, 2, 3, 4 have 4, 1, 4,
3 multi-resolution blocks, respectively.
- [x]  Each branch in the multiresolution group convolution should contain 4 residual units and
each unit should contain two 3×3 convolutions in each resolution
- [x] In fuse block make interpolation like this:
```
torch.nn.functional.interpolate(res, size=[height_output, width_output], mode='bilinear', align_corners=True)
```
- [x]  Rescale with bilinear upsampling and mix the output representations from all the four resolutions through a 1×1 convolution, and produce a 15C-dimensional representation.

*Implementation enhancements:
- [x] Separate fuse block from HighResolutionBlock and merge it with Transition class to improve cleanness and reduce  computation and memory consumption

**Comment by Luonic** [comment]
Solved by [391cc32](https://github.com/Luonic/semi-supervised_semantic_segmentation/commit/391cc3278aa017d2d86cc6a27860bdc30ca6942d)
